spring.application.name=sistema-infracoes

# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SistemaInfracoes;encrypt=true;trustServerCertificate=true
spring.datasource.username=sistema_app
spring.datasource.password=Sistema@12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true